const ANIMATION_DURATION_MS = 500
const ANIMATION_DELAY_MS = 100
const FLY_OFFSET_Y_PX = 20

const SKILL_BAR_GLOW_BLUR_PX = 8
const SKILL_BAR_GLOW_SPREAD_PX = 2
const SKILL_BAR_REVEALED_TRANSFORM = 'scaleX(1)'
const SKILL_BAR_HIDDEN_TRANSFORM = 'scaleX(0)'

export {
	ANIMATION_DELAY_MS,
	ANIMATION_DURATION_MS,
	FLY_OFFSET_Y_PX,
	SKILL_BAR_GLOW_BLUR_PX,
	SKILL_BAR_GLOW_SPREAD_PX,
	SKILL_BAR_HIDDEN_TRANSFORM,
	SKILL_BAR_REVEALED_TRANSFORM,
}
